#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

source /home/jason/.config/herbstluftwm/hc-colors.sh

#xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

# all clients are maximized in their frame, we only want one client per frame
hc set default_frame_layout 2

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload

hc keybind $Mod-Return  spawn st
hc keybind $Mod-Tab     spawn firefox
hc keybind $Mod-q       spawn /home/jason/.config/herbstluftwm/hc-close-window.sh 
hc keybind $Mod-r       spawn /home/jason/.config/herbstluftwm/hc-remove-frame.sh
hc keybind $Mod-s       spawn /home/jason/.config/herbstluftwm/hc-add-frame.sh
hc keybind $Mod-m       spawn /home/jason/.config/herbstluftwm/hc-cycle-hidden.sh 
hc keybind $Mod-u       spawn /home/jason/.config/herbstluftwm/hc-hidden-menu.sh 

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right


hc keybind F1   spawn $HOME/.config/herbstluftwm/hc-volume-control.sh mute 
hc keybind F2   spawn $HOME/.config/herbstluftwm/hc-volume-control.sh down
hc keybind F3   spawn $HOME/.config/herbstluftwm/hc-volume-control.sh up

hc keybind $Mod-p pseudotile toggle

# moving clients between frames
hc keybind $Mod-Shift-h     spawn /home/jason/.config/herbstluftwm/hc-shift-window.sh left
hc keybind $Mod-Shift-j     spawn /home/jason/.config/herbstluftwm/hc-shift-window.sh down
hc keybind $Mod-Shift-k     spawn /home/jason/.config/herbstluftwm/hc-shift-window.sh up
hc keybind $Mod-Shift-l     spawn /home/jason/.config/herbstluftwm/hc-shift-window.sh right

# splitting frames
# create an empty frame at the specified direction
#hc keybind $Mod-s       split   auto  0.5
#hc keybind $Mod-Control-l     split   right   0.5
# let the current frame explode into subframes
#hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.015
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# splitting frames
hc keybind $Mod-Mod4-h       split left 0.5
hc keybind $Mod-Mod4-j       split bottom 0.5
hc keybind $Mod-Mod4-k       split top 0.5
hc keybind $Mod-Mod4-l       split right 0.5


# tags
tag_names=( {1..6} )

for i in ${tag_names[@]} ; do
    hc add "$i"
    hc add "h$i"
    hc keybind "$Mod-$i"       spawn /home/jason/.config/herbstluftwm/hc-use-desktop.sh "$i"
    hc keybind "$Mod-Shift-$i" spawn /home/jason/.config/herbstluftwm/hc-shift-desktop.sh "$i"
done

hc use ${tag_names[0]} 
hc merge_tag default ${tag_names[0]} 

# layouting
#hc keybind $Mod-r remove
#hc keybind $Mod-s floating toggle
hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-f spawn /home/jason/.config/herbstluftwm/hc-set-fullscreen.sh
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
#hc keybind $Mod-space cycle_layout 1 max grid 

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
#hc keybind $Mod-Tab         cycle_all +1
#hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-i jumpto urgent

# theme

#so bare desktop shows through empty frames
hc set frame_bg_transparent 1

hc set frame_bg_active_color $active_color

# normal theme for others is too dark
hc set frame_bg_normal_color $normal_color 

hc attr theme.active.color $active_color
hc attr theme.normal.color $normal_color
hc attr theme.urgent.color $urgent_color
hc attr theme.border_width 2


# always show a border. Window borders overwrite frame borders so only one border is ever shown.
hc set frame_border_width 0
hc set frame_transparent_width 2
hc set always_show_frame 1

# If set don't draw window borders if there is no ambiguity in focus. Disable to prevent inconsisten window borders
hc set smart_window_surroundings 0

# If set don't draw frame borders if there is no ambiguity in focus. Disable to prevent inconsisten window borders
hc set smart_frame_surroundings 0

# if set only pagers and task bars can request focus change. No difference noticed
hc set focus_stealing_prevention 0

# mouse focuses whichever window it hovers over
hc set focus_follows_mouse 1

# rules

#unset all rules
hc unrule -F

# turn on pseudotiling for splash windows. Splash windows often look bad when forced to scale to their frame.
hc rule windowtype='_NET_WM_WINDOW_TYPE_SPLASH' --pseudotile=on

# give focus to new dialogs
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' --focus=on

# don't manage desktop utility windows. Leaving those windows managed doesn't seem to have any effect on WM behaviour for some reason.
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' --manage=off

# pad top of the monitor so there is a gap between the status bar and the WM content
hc pad 0 24

# gap between frames and egde of monitor
hc set frame_gap 24 

# unlock, just to be sure
hc unlock

# set styling for pretty printed herbstluftwm object trees
#hc set tree_style '╾│ ├└╼─┐'
#hc set tree_style '-| |\"---.'

if ! pstree $PPID | grep -q lemonbar; then
    $HOME/.config/herbstluftwm/lemonbar/hc-lemonbar.sh &
fi

if ! pstree $PPID | grep -q hc-event-listener.sh; then
    $HOME/.config/herbstluftwm/hc-event-listener.sh &
fi

if ! pstree $PPID | grep -q compton; then
    compton &
fi

feh --bg-center $HOME/.backgrounds/blue-blocks-cavern.jpg
